#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for VECTRA-PLAYER Path Migration

set -e

echo "========================================"
echo "Path Migration Script - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/home/devops/Desktop/VECTRA-PLAYER"

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python virtual environment
if [ ! -d "$PROJECT_ROOT/.venv" ]; then
    echo -e "${RED}Virtual environment not found at $PROJECT_ROOT/.venv${NC}"
    echo "Please create it first: python3 -m venv .venv"
    exit 1
fi

echo -e "${GREEN}✓ Virtual environment found${NC}"

# ============================================
# ACTIVATE VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo "Activating virtual environment..."
source "$PROJECT_ROOT/.venv/bin/activate"
echo -e "${GREEN}✓ Virtual environment activated${NC}"

# ============================================
# VERIFY DEPENDENCIES
# ============================================

echo ""
echo "Verifying Python dependencies..."

# Check if pytest is available (for testing)
if ! python -c "import pytest" 2>/dev/null; then
    echo -e "${YELLOW}Warning: pytest not found. Tests may not run.${NC}"
else
    echo -e "${GREEN}✓ pytest available${NC}"
fi

# Check if ruff is available (for linting)
if ! command -v ruff &> /dev/null; then
    echo -e "${YELLOW}Warning: ruff not found. Linting may not work.${NC}"
else
    echo -e "${GREEN}✓ ruff available${NC}"
fi

# ============================================
# ENVIRONMENT READY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: VECTRA-PLAYER Path Migration"
echo "Working Directory: $PROJECT_ROOT"
echo ""
echo "Available Commands:"
echo "  python scripts/migrate_paths.py --help       Show help"
echo "  python scripts/migrate_paths.py --dry-run    Preview changes"
echo "  python scripts/migrate_paths.py --execute    Execute migration"
echo "  python scripts/migrate_paths.py --rollback   Rollback migration"
echo ""
echo "Testing:"
echo "  cd src && ../.venv/bin/python -m pytest tests/test_scripts/test_migrate_paths.py -v"
echo ""
echo "Linting:"
echo "  ruff check scripts/migrate_paths.py"
echo ""
echo "========================================"
echo ""
