#!/usr/bin/env bash
# Validate that commit messages start with VEC-NNN: prefix.
# Used as a commit-msg hook via pre-commit.
#
# Allowed patterns:
#   - VEC-NNN: <message> (e.g., "VEC-001: pin rugs-feed deps")
#   - Merge commits (auto-generated by git)
#   - Revert commits (auto-generated by git)
#
# Exit codes:
#   0 = valid
#   1 = invalid

set -euo pipefail

COMMIT_MSG_FILE="$1"

if [ ! -f "$COMMIT_MSG_FILE" ]; then
    echo "ERROR: Commit message file not found: $COMMIT_MSG_FILE"
    exit 1
fi

# Read first line of commit message
FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

# Allow merge commits
if echo "$FIRST_LINE" | grep -qE '^Merge '; then
    exit 0
fi

# Allow revert commits
if echo "$FIRST_LINE" | grep -qE '^Revert '; then
    exit 0
fi

# Validate VEC-NNN: prefix
if echo "$FIRST_LINE" | grep -qE '^VEC-[0-9]+: .+'; then
    exit 0
fi

echo "BLOCK: Commit message must start with VEC-NNN: prefix."
echo "  Got: $FIRST_LINE"
echo "  Required: VEC-NNN: <description> (e.g., 'VEC-001: pin rugs-feed deps')"
echo ""
echo "Active projects:"
if [ -f "governance/projects/registry.json" ]; then
    # Show active project IDs
    python3 -c "
import json, sys
try:
    with open('governance/projects/registry.json') as f:
        reg = json.load(f)
    for pid, proj in reg.get('projects', {}).items():
        if proj.get('status') == 'active':
            print(f'  {pid}: {proj[\"title\"]}')
except Exception:
    print('  (could not read registry)')
" 2>/dev/null || echo "  (could not read registry)"
fi
exit 1
